//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ulatina.PrograAvanzada.AplicacionWeb.OperacionesMatematicas {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CompositeType", Namespace="http://schemas.datacontract.org/2004/07/Ulatina.PrograAvanzada.BLAplicacionWeb")]
    [System.SerializableAttribute()]
    public partial class CompositeType : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool BoolValueField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string StringValueField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool BoolValue {
            get {
                return this.BoolValueField;
            }
            set {
                if ((this.BoolValueField.Equals(value) != true)) {
                    this.BoolValueField = value;
                    this.RaisePropertyChanged("BoolValue");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string StringValue {
            get {
                return this.StringValueField;
            }
            set {
                if ((object.ReferenceEquals(this.StringValueField, value) != true)) {
                    this.StringValueField = value;
                    this.RaisePropertyChanged("StringValue");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="OperacionesMatematicas.IService1")]
    public interface IService1 {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/Sume", ReplyAction="http://tempuri.org/IService1/SumeResponse")]
        double Sume(double elOperandoUno, double elOperandoDos);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/Sume", ReplyAction="http://tempuri.org/IService1/SumeResponse")]
        System.Threading.Tasks.Task<double> SumeAsync(double elOperandoUno, double elOperandoDos);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/Reste", ReplyAction="http://tempuri.org/IService1/ResteResponse")]
        double Reste(double elOperandoUno, double elOperandoDos);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/Reste", ReplyAction="http://tempuri.org/IService1/ResteResponse")]
        System.Threading.Tasks.Task<double> ResteAsync(double elOperandoUno, double elOperandoDos);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/Multiplique", ReplyAction="http://tempuri.org/IService1/MultipliqueResponse")]
        double Multiplique(double elOperandoUno, double elOperandoDos);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/Multiplique", ReplyAction="http://tempuri.org/IService1/MultipliqueResponse")]
        System.Threading.Tasks.Task<double> MultipliqueAsync(double elOperandoUno, double elOperandoDos);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/Divide", ReplyAction="http://tempuri.org/IService1/DivideResponse")]
        double Divide(double elOperandoUno, double elOperandoDos);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/Divide", ReplyAction="http://tempuri.org/IService1/DivideResponse")]
        System.Threading.Tasks.Task<double> DivideAsync(double elOperandoUno, double elOperandoDos);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/WhatDateIsToday", ReplyAction="http://tempuri.org/IService1/WhatDateIsTodayResponse")]
        string WhatDateIsToday();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/WhatDateIsToday", ReplyAction="http://tempuri.org/IService1/WhatDateIsTodayResponse")]
        System.Threading.Tasks.Task<string> WhatDateIsTodayAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetData", ReplyAction="http://tempuri.org/IService1/GetDataResponse")]
        string GetData(int value);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetData", ReplyAction="http://tempuri.org/IService1/GetDataResponse")]
        System.Threading.Tasks.Task<string> GetDataAsync(int value);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetDataUsingDataContract", ReplyAction="http://tempuri.org/IService1/GetDataUsingDataContractResponse")]
        Ulatina.PrograAvanzada.AplicacionWeb.OperacionesMatematicas.CompositeType GetDataUsingDataContract(Ulatina.PrograAvanzada.AplicacionWeb.OperacionesMatematicas.CompositeType composite);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetDataUsingDataContract", ReplyAction="http://tempuri.org/IService1/GetDataUsingDataContractResponse")]
        System.Threading.Tasks.Task<Ulatina.PrograAvanzada.AplicacionWeb.OperacionesMatematicas.CompositeType> GetDataUsingDataContractAsync(Ulatina.PrograAvanzada.AplicacionWeb.OperacionesMatematicas.CompositeType composite);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IService1Channel : Ulatina.PrograAvanzada.AplicacionWeb.OperacionesMatematicas.IService1, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class Service1Client : System.ServiceModel.ClientBase<Ulatina.PrograAvanzada.AplicacionWeb.OperacionesMatematicas.IService1>, Ulatina.PrograAvanzada.AplicacionWeb.OperacionesMatematicas.IService1 {
        
        public Service1Client() {
        }
        
        public Service1Client(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public Service1Client(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public double Sume(double elOperandoUno, double elOperandoDos) {
            return base.Channel.Sume(elOperandoUno, elOperandoDos);
        }
        
        public System.Threading.Tasks.Task<double> SumeAsync(double elOperandoUno, double elOperandoDos) {
            return base.Channel.SumeAsync(elOperandoUno, elOperandoDos);
        }
        
        public double Reste(double elOperandoUno, double elOperandoDos) {
            return base.Channel.Reste(elOperandoUno, elOperandoDos);
        }
        
        public System.Threading.Tasks.Task<double> ResteAsync(double elOperandoUno, double elOperandoDos) {
            return base.Channel.ResteAsync(elOperandoUno, elOperandoDos);
        }
        
        public double Multiplique(double elOperandoUno, double elOperandoDos) {
            return base.Channel.Multiplique(elOperandoUno, elOperandoDos);
        }
        
        public System.Threading.Tasks.Task<double> MultipliqueAsync(double elOperandoUno, double elOperandoDos) {
            return base.Channel.MultipliqueAsync(elOperandoUno, elOperandoDos);
        }
        
        public double Divide(double elOperandoUno, double elOperandoDos) {
            return base.Channel.Divide(elOperandoUno, elOperandoDos);
        }
        
        public System.Threading.Tasks.Task<double> DivideAsync(double elOperandoUno, double elOperandoDos) {
            return base.Channel.DivideAsync(elOperandoUno, elOperandoDos);
        }
        
        public string WhatDateIsToday() {
            return base.Channel.WhatDateIsToday();
        }
        
        public System.Threading.Tasks.Task<string> WhatDateIsTodayAsync() {
            return base.Channel.WhatDateIsTodayAsync();
        }
        
        public string GetData(int value) {
            return base.Channel.GetData(value);
        }
        
        public System.Threading.Tasks.Task<string> GetDataAsync(int value) {
            return base.Channel.GetDataAsync(value);
        }
        
        public Ulatina.PrograAvanzada.AplicacionWeb.OperacionesMatematicas.CompositeType GetDataUsingDataContract(Ulatina.PrograAvanzada.AplicacionWeb.OperacionesMatematicas.CompositeType composite) {
            return base.Channel.GetDataUsingDataContract(composite);
        }
        
        public System.Threading.Tasks.Task<Ulatina.PrograAvanzada.AplicacionWeb.OperacionesMatematicas.CompositeType> GetDataUsingDataContractAsync(Ulatina.PrograAvanzada.AplicacionWeb.OperacionesMatematicas.CompositeType composite) {
            return base.Channel.GetDataUsingDataContractAsync(composite);
        }
    }
}
